_wandb:
    value:
        cli_version: 0.21.1
        e:
            6pdwy3amvap7zzmuwlhnzkwxdntz3wel:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "19327352832"
                codePath: src/main.py
                codePathLocal: src/main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "426965938176"
                email: anjali.sarawgi9@gmail.com
                executable: /Users/anjalisarawgi/anaconda3/envs/gnn_hre/bin/python
                git:
                    commit: 6b81467d4a75be892d6bef24aa953f3218b0f2b2
                    remote: https://github.com/anjalisarawgi/gnns-netlist-re.git
                host: g158.lmu.vpn.lrz.de
                memory:
                    total: "8589934592"
                os: macOS-14.5-arm64-arm-64bit
                program: src/main.py
                python: CPython 3.8.20
                root: /Users/anjalisarawgi/Documents/gnns_hre/thesis/gnns-netlist-re
                startedAt: "2025-09-02T15:50:13.090726Z"
                writerId: 6pdwy3amvap7zzmuwlhnzkwxdntz3wel
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 13
                - 16
            "4": 3.8.20
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
batch_size:
    value: 5000
dataset:
    value: aes_cipher_top_single_gml
epochs:
    value: 1000
hidden_channels:
    value: 256
lr:
    value: 0.01
model:
    value: graphSAGE
walk_length:
    value: 3
