sampling_method: "graphsaint_rw"
model: "gat"

train_gml:
  -  "graphs/processed_v2/chacha-master/gscl45nm/chacha_core_combined_m2.gml"
  -  "graphs/processed_v2/chacha-master/gscl45nm/chacha_combined_m2.gml"
  -  "graphs/processed_v2/chacha-master/osu035/chacha_core_combined_m2.gml"
  -  "graphs/processed_v2/chacha-master/osu035/chacha_combined_m2.gml"
  -  "graphs/processed_v2/cmac-master/gscl45nm/cmac_combined_m2.gml"
  -  "graphs/processed_v2/cmac-master/osu035/cmac_combined_m2.gml"
  # -  "graphs/processed_v2/aes-master/gscl45nm/aes_core_combined_m2.gml"
  # -  "graphs/processed_v2/aes-master/gscl45nm/aes_decipher_block_combined_m2.gml"
  # -  "graphs/processed_v2/aes-master/osu035/aes_core_combined_m2.gml"
  # -  "graphs/processed_v2/aes-master/osu035/aes_decipher_block_combined_m2.gml"
  -  "graphs/processed_v2/gcm-aes_latest/nangate/aes_key_expand_128_combined_m2.gml"
  -  "graphs/processed_v2/gcm-aes_latest/nangate/aes_cipher_top_combined_m2.gml"
  -  "graphs/processed_v2/gcm-aes_latest/gscl45nm/aes_key_expand_128_combined_m2.gml"
  -  "graphs/processed_v2/gcm-aes_latest/gscl45nm/gcm_aes_v0_combined_m2.gml"
  -  "graphs/processed_v2/gcm-aes_latest/gscl45nm/aes_cipher_top_combined_m2.gml"
  -  "graphs/processed_v2/gcm-aes_latest/osu035/aes_key_expand_128_combined_m2.gml"
  -  "graphs/processed_v2/gcm-aes_latest/osu035/gcm_aes_v0_combined_m2.gml"
  -  "graphs/processed_v2/gcm-aes_latest/osu035/aes_cipher_top_combined_m2.gml"
  

test_gml: "graphs/processed_v2/tiny_aes_latest/osu035/aes_128_combined_m2.gml"

epochs: 1000
label_mode: "boundary"
walk_length: 10
perc_batchsize: 0.01

set_gradient_clipping: true
normalize_class_weights: true
reduction_method_cel : "sum"
lr : 0.001