sampling_method: "graphsaint_rw"
model: "gat"

train_gml: 
- "graphs/processed_v2/aes-master/gscl45nm/aes_core_combined_m1.gml"
    

test_gml:    "graphs/processed_v2/aes-master/nangate/aes_core_combined_m1.gml"

epochs: 100
walk_length: 20
perc_batchsize: 0.01
# num_steps: 1
# radius: 7
# num_subgraphs: 8000

set_gradient_clipping: true
normalize_class_weights: true