sampling_method: graphsaint_rw
model: gat

train_gml:
- "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/gscl45nm/aes_cipher_top_combined_m1.gml"
# - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/gscl45nm/aes_inv_cipher_top_combined_m1.gml"
# - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/gscl45nm/aes_inv_sbox_combined_m1.gml"
- "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/gscl45nm/aes_key_expand_128_combined_m1.gml"
# - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/gscl45nm/aes_sbox_combined_m1.gml"
- "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/nangate/aes_cipher_top_combined_m1.gml"
- "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/nangate/aes_inv_cipher_top_combined_m1.gml"
# - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/nangate/aes_inv_sbox_combined_m1.gml"
# - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/nangate/aes_key_expand_128_combined_m1.gml"
# - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/nangate/aes_sbox_combined_m1.gml"
- "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/osu035/aes_cipher_top_combined_m1.gml"
- "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/osu035/aes_inv_cipher_top_combined_m1.gml"
# - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/osu035/aes_inv_sbox_combined_m1.gml"
- "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/osu035/aes_key_expand_128_combined_m1.gml"

val_gml: 
#  - "new_graphs_crypto/processed_partitions_boundaryM1/tiny_aes_latest/osu035/aes_128_combined_m1.gml"
 - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/gscl45nm/aes_inv_cipher_top_combined_m1.gml"
 - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/nangate/aes_key_expand_128_combined_m1.gml"
#  - "new_graphs_crypto/processed_partitions_boundaryM1/des_latest/gscl45nm/des_combined_m1.gml"



test_gml: 
 - "new_graphs_crypto/processed_partitions_boundaryM1/tiny_aes_latest/osu035/aes_128_combined_m1.gml"
 - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/gscl45nm/aes_inv_cipher_top_combined_m1.gml"
 - "new_graphs_crypto/processed_partitions_boundaryM1/aes_core/nangate/aes_key_expand_128_combined_m1.gml"
 - "new_graphs_crypto/processed_partitions_boundaryM1/des_latest/gscl45nm/des_combined_m1.gml"


epochs: 1000
walk_length: 20
perc_batchsize: 0.01
set_gradient_clipping: true
normalize_class_weights: true
reduction_method_cel: "mean"
lr: 0.003
loss_type : "ce_weighted" #ce_weighted
sample_coverage : 50