top_k: 15
n_estimators: 100
# use_partition_features: true
save_models: true
save_predictions: true
output_dir: results/rf/lodo/aes_enc


train_gml:
# # === aes_core ===
# - "graphs_final/crypto_graphs_final/aes_core/nangate/aes_key_expand_128_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/nangate/aes_inv_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/nangate/aes_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/gscl45nm/aes_key_expand_128_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/gscl45nm/aes_inv_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/gscl45nm/aes_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/osu035/aes_key_expand_128_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/osu035/aes_inv_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/osu035/aes_cipher_top_combined_m1.gml"

# # # === aes-master ===
- "graphs_final/other_graphs_final/aes-master/gscl45nm/aes_core_combined_m1.gml"
# - "graphs_final/other_graphs_final/aes-master/gscl45nm/aes_decipher_block_combined_m1.gml"
- "graphs_final/other_graphs_final/aes-master/osu035/aes_core_combined_m1.gml"
- "graphs_final/other_graphs_final/aes-master/osu035/aes_decipher_block_combined_m1.gml"

# # # === aes-encryption_latest ===
# - "graphs_final/crypto_graphs_final/aes-encryption_latest/nangate/aes_key_expand_128_combined_m1.gml"
# - "graphs_final/crypto_graphs_final/aes-encryption_latest/nangate/aes_cipher_top_combined_m1.gml"
# - "graphs_final/crypto_graphs_final/aes-encryption_latest/gscl45nm/aes_key_expand_128_combined_m1.gml"
# - "graphs_final/crypto_graphs_final/aes-encryption_latest/gscl45nm/aes_cipher_top_combined_m1.gml"
# # - "graphs_final/crypto_graphs_final/aes-encryption_latest/osu035/aes_key_expand_128_combined_m1.gml"
# - "graphs_final/crypto_graphs_final/aes-encryption_latest/osu035/aes_cipher_top_combined_m1.gml"

# # # === apbtoaes128_latest ===
# - "graphs_final/other_graphs_final/apbtoaes128_latest/nangate/aes_core_combined_m1.gml"
- "graphs_final/other_graphs_final/apbtoaes128_latest/gscl45nm/aes_core_combined_m1.gml"
- "graphs_final/other_graphs_final/apbtoaes128_latest/osu035/aes_core_combined_m1.gml"

# # === gcm-aes_latest ===
- "graphs_final/crypto_graphs_final/gcm-aes_latest/nangate/aes_key_expand_128_combined_m1.gml"
# - "graphs_final/crypto_graphs_final/gcm-aes_latest/nangate/gcm_aes_v0_combined_m1.gml"
- "graphs_final/crypto_graphs_final/gcm-aes_latest/nangate/aes_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/gcm-aes_latest/gscl45nm/aes_key_expand_128_combined_m1.gml"
- "graphs_final/crypto_graphs_final/gcm-aes_latest/gscl45nm/gcm_aes_v0_combined_m1.gml"
- "graphs_final/crypto_graphs_final/gcm-aes_latest/gscl45nm/aes_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/gcm-aes_latest/osu035/aes_key_expand_128_combined_m1.gml"
- "graphs_final/crypto_graphs_final/gcm-aes_latest/osu035/gcm_aes_v0_combined_m1.gml"
- "graphs_final/crypto_graphs_final/gcm-aes_latest/osu035/aes_cipher_top_combined_m1.gml"

val_gml:
- "graphs_final/crypto_graphs_final/gcm-aes_latest/nangate/gcm_aes_v0_combined_m1.gml"
- "graphs_final/other_graphs_final/apbtoaes128_latest/nangate/aes_core_combined_m1.gml"
# - "graphs_final/crypto_graphs_final/aes-encryption_latest/osu035/aes_key_expand_128_combined_m1.gml"
- "graphs_final/other_graphs_final/aes-master/gscl45nm/aes_decipher_block_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes_core/nangate/aes_key_expand_128_combined_m1.gml"



test_gml:
# # === aes-encryption_latest ===
- "graphs_final/crypto_graphs_final/aes-encryption_latest/nangate/aes_key_expand_128_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes-encryption_latest/nangate/aes_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes-encryption_latest/gscl45nm/aes_key_expand_128_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes-encryption_latest/gscl45nm/aes_cipher_top_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes-encryption_latest/osu035/aes_key_expand_128_combined_m1.gml"
- "graphs_final/crypto_graphs_final/aes-encryption_latest/osu035/aes_cipher_top_combined_m1.gml"

